/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final_othello;
import clases.nodos;
import clases.tablero;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
/**
 *
 * @author dieg_
 */
public class FrmTablero extends javax.swing.JFrame {

    /**
     * Creates new form FrmTablero
     */
    tablero tablero1= new tablero();
    boolean val;
            
    Image imb= new ImageIcon("src/imagenes/fichaBlanca.png").getImage();
    Image imn= new ImageIcon("src/imagenes/fichaNegra.png").getImage();
    public FrmTablero() {
        initComponents();
        
        /*nodos N1_1= new nodos("1_1", -1); nodos N1_2= new nodos("1_2", -1); nodos N1_3= new nodos("1_3", -1);
        
        nodos N2_1= new nodos("2_1", -1); nodos N2_2= new nodos("2_2", -1); nodos N2_3= new nodos("2_3", -1);
        
        nodos N3_1= new nodos("3_1", -1); nodos N3_2= new nodos("3_2", -1); nodos N3_3= new nodos("3_3", -1);*/
        
        tablero1.agregarAlFinal("1_1", -1);  System.out.println("1");
        tablero1.agregarAlFinal("1_2", -1);  System.out.println("2");
        tablero1.agregarAlFinal("1_3", -1);  System.out.println("3");
        
        tablero1.agregarAlFinal("2_1", -1);  tablero1.agregarAlFinal("2_2", -1);  tablero1.agregarAlFinal("2_3", -1);
        
        tablero1.agregarAlFinal("3_1", -1);  tablero1.agregarAlFinal("3_2", -1);  tablero1.agregarAlFinal("3_3", -1);
        
        tablero1.mostrarTodo();
        
        btn1_1.addActionListener(actionListener);
        btn1_2.addActionListener(actionListener);
        btn1_3.addActionListener(actionListener);
        
        btn2_1.addActionListener(actionListener);
        btn2_2.addActionListener(actionListener);
        btn2_3.addActionListener(actionListener);
        
        btn3_1.addActionListener(actionListener);
        btn3_2.addActionListener(actionListener);
        btn3_3.addActionListener(actionListener);
        pintar();
    }
    
    public void pintar(){
        /*for(JButton b:jPanel2.getComponents()){
            
        }*/
        System.out.println("cantidad componentes " + jPanel2.getComponents().length);
        
    }
    
    ActionListener actionListener = (ActionEvent actionEvent) -> {
        //System.out.println("Jugador actual "+ jActual);
        //asignacionJugadores();
        JButton botonRe = (JButton) actionEvent.getSource();
        
        //activosBtn.clear();
        //revisionRutinaria(botonRe);
        //accion(botonRe);
        val=!val;
        //nombres();
       // revisionInicial();
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn1_1 = new javax.swing.JButton();
        btn1_3 = new javax.swing.JButton();
        btn1_4 = new javax.swing.JButton();
        btn1_5 = new javax.swing.JButton();
        btn5_3 = new javax.swing.JButton();
        btn1_6 = new javax.swing.JButton();
        btn5_7 = new javax.swing.JButton();
        btn1_7 = new javax.swing.JButton();
        btn5_4 = new javax.swing.JButton();
        btn6_1 = new javax.swing.JButton();
        btn8_1 = new javax.swing.JButton();
        btn8_3 = new javax.swing.JButton();
        btn8_2 = new javax.swing.JButton();
        btn8_8 = new javax.swing.JButton();
        btn3_2 = new javax.swing.JButton();
        btn8_5 = new javax.swing.JButton();
        btn6_6 = new javax.swing.JButton();
        btn3_3 = new javax.swing.JButton();
        btn6_3 = new javax.swing.JButton();
        btn8_4 = new javax.swing.JButton();
        btn6_8 = new javax.swing.JButton();
        btn6_5 = new javax.swing.JButton();
        btn6_7 = new javax.swing.JButton();
        btn6_4 = new javax.swing.JButton();
        btn6_2 = new javax.swing.JButton();
        btn7_2 = new javax.swing.JButton();
        btn7_3 = new javax.swing.JButton();
        btn7_8 = new javax.swing.JButton();
        btn3_4 = new javax.swing.JButton();
        btn8_6 = new javax.swing.JButton();
        btn3_5 = new javax.swing.JButton();
        btn3_6 = new javax.swing.JButton();
        btn3_7 = new javax.swing.JButton();
        btn3_8 = new javax.swing.JButton();
        btn4_1 = new javax.swing.JButton();
        btn4_2 = new javax.swing.JButton();
        btn1_8 = new javax.swing.JButton();
        btn4_3 = new javax.swing.JButton();
        btn7_7 = new javax.swing.JButton();
        btn4_4 = new javax.swing.JButton();
        btn2_1 = new javax.swing.JButton();
        btn7_1 = new javax.swing.JButton();
        btn2_2 = new javax.swing.JButton();
        btn7_5 = new javax.swing.JButton();
        btn2_3 = new javax.swing.JButton();
        btn7_4 = new javax.swing.JButton();
        btn2_4 = new javax.swing.JButton();
        btn7_6 = new javax.swing.JButton();
        btn4_5 = new javax.swing.JButton();
        btn4_6 = new javax.swing.JButton();
        btn4_7 = new javax.swing.JButton();
        btn4_8 = new javax.swing.JButton();
        btn5_1 = new javax.swing.JButton();
        btn5_2 = new javax.swing.JButton();
        btn5_5 = new javax.swing.JButton();
        btn5_8 = new javax.swing.JButton();
        btn2_5 = new javax.swing.JButton();
        btn5_6 = new javax.swing.JButton();
        btn8_7 = new javax.swing.JButton();
        btn1_2 = new javax.swing.JButton();
        btn2_6 = new javax.swing.JButton();
        btn2_7 = new javax.swing.JButton();
        btn2_8 = new javax.swing.JButton();
        btn3_1 = new javax.swing.JButton();
        lbl_actual = new javax.swing.JLabel();
        lbl_actual_icon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        btn1_1.setBackground(new java.awt.Color(29, 191, 44));
        btn1_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_1.setName("1_1"); // NOI18N

        btn1_3.setBackground(new java.awt.Color(29, 191, 44));
        btn1_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_3.setName("1_3"); // NOI18N

        btn1_4.setBackground(new java.awt.Color(29, 191, 44));
        btn1_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_4.setName("1_4"); // NOI18N

        btn1_5.setBackground(new java.awt.Color(29, 191, 44));
        btn1_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_5.setName("1_5"); // NOI18N

        btn5_3.setBackground(new java.awt.Color(29, 191, 44));
        btn5_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn5_3.setName("5_3"); // NOI18N

        btn1_6.setBackground(new java.awt.Color(29, 191, 44));
        btn1_6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_6.setName("1_6"); // NOI18N

        btn5_7.setBackground(new java.awt.Color(29, 191, 44));
        btn5_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn5_7.setName("5_7"); // NOI18N

        btn1_7.setBackground(new java.awt.Color(29, 191, 44));
        btn1_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_7.setName("1_7"); // NOI18N

        btn5_4.setBackground(new java.awt.Color(29, 191, 44));
        btn5_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn5_4.setName("5_4"); // NOI18N

        btn6_1.setBackground(new java.awt.Color(29, 191, 44));
        btn6_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn6_1.setName("6_1"); // NOI18N

        btn8_1.setBackground(new java.awt.Color(29, 191, 44));
        btn8_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_1.setName("8_1"); // NOI18N

        btn8_3.setBackground(new java.awt.Color(29, 191, 44));
        btn8_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_3.setName("8_3"); // NOI18N

        btn8_2.setBackground(new java.awt.Color(29, 191, 44));
        btn8_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_2.setName("8_2"); // NOI18N

        btn8_8.setBackground(new java.awt.Color(29, 191, 44));
        btn8_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_8.setName("8_8"); // NOI18N

        btn3_2.setBackground(new java.awt.Color(29, 191, 44));
        btn3_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn3_2.setName("3_2"); // NOI18N

        btn8_5.setBackground(new java.awt.Color(29, 191, 44));
        btn8_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_5.setName("8_5"); // NOI18N

        btn6_6.setBackground(new java.awt.Color(29, 191, 44));
        btn6_6.setName("6_6"); // NOI18N

        btn3_3.setBackground(new java.awt.Color(29, 191, 44));
        btn3_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn3_3.setName("3_3"); // NOI18N

        btn6_3.setBackground(new java.awt.Color(29, 191, 44));
        btn6_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn6_3.setName("6_3"); // NOI18N

        btn8_4.setBackground(new java.awt.Color(29, 191, 44));
        btn8_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_4.setName("8_4"); // NOI18N

        btn6_8.setBackground(new java.awt.Color(29, 191, 44));
        btn6_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn6_8.setName("6_8"); // NOI18N

        btn6_5.setBackground(new java.awt.Color(29, 191, 44));
        btn6_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn6_5.setName("6_5"); // NOI18N

        btn6_7.setBackground(new java.awt.Color(29, 191, 44));
        btn6_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn6_7.setName("6_7"); // NOI18N

        btn6_4.setBackground(new java.awt.Color(29, 191, 44));
        btn6_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn6_4.setName("6_4"); // NOI18N

        btn6_2.setBackground(new java.awt.Color(29, 191, 44));
        btn6_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn6_2.setName("6_2"); // NOI18N

        btn7_2.setBackground(new java.awt.Color(29, 191, 44));
        btn7_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_2.setName("7_2"); // NOI18N

        btn7_3.setBackground(new java.awt.Color(29, 191, 44));
        btn7_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_3.setName("7_3"); // NOI18N

        btn7_8.setBackground(new java.awt.Color(29, 191, 44));
        btn7_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_8.setName("7_8"); // NOI18N

        btn3_4.setBackground(new java.awt.Color(29, 191, 44));
        btn3_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn3_4.setName("3_4"); // NOI18N

        btn8_6.setBackground(new java.awt.Color(29, 191, 44));
        btn8_6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_6.setName("8_6"); // NOI18N

        btn3_5.setBackground(new java.awt.Color(29, 191, 44));
        btn3_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn3_5.setName("3_5"); // NOI18N

        btn3_6.setBackground(new java.awt.Color(29, 191, 44));
        btn3_6.setName("3_6"); // NOI18N

        btn3_7.setBackground(new java.awt.Color(29, 191, 44));
        btn3_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn3_7.setName("3_7"); // NOI18N

        btn3_8.setBackground(new java.awt.Color(29, 191, 44));
        btn3_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn3_8.setName("3_8"); // NOI18N

        btn4_1.setBackground(new java.awt.Color(29, 191, 44));
        btn4_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn4_1.setName("4_1"); // NOI18N

        btn4_2.setBackground(new java.awt.Color(29, 191, 44));
        btn4_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn4_2.setName("4_2"); // NOI18N

        btn1_8.setBackground(new java.awt.Color(29, 191, 44));
        btn1_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_8.setName("1_8"); // NOI18N

        btn4_3.setBackground(new java.awt.Color(29, 191, 44));
        btn4_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn4_3.setName("4_3"); // NOI18N

        btn7_7.setBackground(new java.awt.Color(29, 191, 44));
        btn7_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_7.setName("7_7"); // NOI18N

        btn4_4.setBackground(new java.awt.Color(29, 191, 44));
        btn4_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn4_4.setName("4_4"); // NOI18N

        btn2_1.setBackground(new java.awt.Color(29, 191, 44));
        btn2_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_1.setName("2_1"); // NOI18N

        btn7_1.setBackground(new java.awt.Color(29, 191, 44));
        btn7_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_1.setName("7_1"); // NOI18N

        btn2_2.setBackground(new java.awt.Color(29, 191, 44));
        btn2_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_2.setName("2_2"); // NOI18N

        btn7_5.setBackground(new java.awt.Color(29, 191, 44));
        btn7_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_5.setName("7_5"); // NOI18N

        btn2_3.setBackground(new java.awt.Color(29, 191, 44));
        btn2_3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_3.setName("2_3"); // NOI18N

        btn7_4.setBackground(new java.awt.Color(29, 191, 44));
        btn7_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_4.setName("7_4"); // NOI18N

        btn2_4.setBackground(new java.awt.Color(29, 191, 44));
        btn2_4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_4.setName("2_4"); // NOI18N

        btn7_6.setBackground(new java.awt.Color(29, 191, 44));
        btn7_6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn7_6.setName("7_6"); // NOI18N

        btn4_5.setBackground(new java.awt.Color(29, 191, 44));
        btn4_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn4_5.setName("4_5"); // NOI18N

        btn4_6.setBackground(new java.awt.Color(29, 191, 44));
        btn4_6.setName("4_6"); // NOI18N

        btn4_7.setBackground(new java.awt.Color(29, 191, 44));
        btn4_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn4_7.setName("4_7"); // NOI18N

        btn4_8.setBackground(new java.awt.Color(29, 191, 44));
        btn4_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn4_8.setName("4_8"); // NOI18N

        btn5_1.setBackground(new java.awt.Color(29, 191, 44));
        btn5_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn5_1.setName("5_1"); // NOI18N

        btn5_2.setBackground(new java.awt.Color(29, 191, 44));
        btn5_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn5_2.setName("5_2"); // NOI18N

        btn5_5.setBackground(new java.awt.Color(29, 191, 44));
        btn5_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn5_5.setName("5_5"); // NOI18N

        btn5_8.setBackground(new java.awt.Color(29, 191, 44));
        btn5_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn5_8.setName("5_8"); // NOI18N

        btn2_5.setBackground(new java.awt.Color(29, 191, 44));
        btn2_5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_5.setName("2_5"); // NOI18N

        btn5_6.setBackground(new java.awt.Color(29, 191, 44));
        btn5_6.setName("5_6"); // NOI18N

        btn8_7.setBackground(new java.awt.Color(29, 191, 44));
        btn8_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn8_7.setName("8_7"); // NOI18N

        btn1_2.setBackground(new java.awt.Color(29, 191, 44));
        btn1_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1_2.setName("1_2"); // NOI18N

        btn2_6.setBackground(new java.awt.Color(29, 191, 44));
        btn2_6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_6.setName("2_6"); // NOI18N

        btn2_7.setBackground(new java.awt.Color(29, 191, 44));
        btn2_7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_7.setName("2_7"); // NOI18N

        btn2_8.setBackground(new java.awt.Color(29, 191, 44));
        btn2_8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn2_8.setName("2_8"); // NOI18N

        btn3_1.setBackground(new java.awt.Color(29, 191, 44));
        btn3_1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn3_1.setName("3_1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_actual.setBackground(new java.awt.Color(29, 191, 44));
        lbl_actual.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_actual.setForeground(new java.awt.Color(102, 102, 102));
        lbl_actual.setText("Nombre Jugador");

        lbl_actual_icon.setForeground(new java.awt.Color(153, 153, 153));
        lbl_actual_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_actual_icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lbl_actual_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_actual_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1_1;
    private javax.swing.JButton btn1_2;
    private javax.swing.JButton btn1_3;
    private javax.swing.JButton btn1_4;
    private javax.swing.JButton btn1_5;
    private javax.swing.JButton btn1_6;
    private javax.swing.JButton btn1_7;
    private javax.swing.JButton btn1_8;
    private javax.swing.JButton btn2_1;
    private javax.swing.JButton btn2_2;
    private javax.swing.JButton btn2_3;
    private javax.swing.JButton btn2_4;
    private javax.swing.JButton btn2_5;
    private javax.swing.JButton btn2_6;
    private javax.swing.JButton btn2_7;
    private javax.swing.JButton btn2_8;
    private javax.swing.JButton btn3_1;
    private javax.swing.JButton btn3_2;
    private javax.swing.JButton btn3_3;
    private javax.swing.JButton btn3_4;
    private javax.swing.JButton btn3_5;
    private javax.swing.JButton btn3_6;
    private javax.swing.JButton btn3_7;
    private javax.swing.JButton btn3_8;
    private javax.swing.JButton btn4_1;
    private javax.swing.JButton btn4_2;
    private javax.swing.JButton btn4_3;
    private javax.swing.JButton btn4_4;
    private javax.swing.JButton btn4_5;
    private javax.swing.JButton btn4_6;
    private javax.swing.JButton btn4_7;
    private javax.swing.JButton btn4_8;
    private javax.swing.JButton btn5_1;
    private javax.swing.JButton btn5_2;
    private javax.swing.JButton btn5_3;
    private javax.swing.JButton btn5_4;
    private javax.swing.JButton btn5_5;
    private javax.swing.JButton btn5_6;
    private javax.swing.JButton btn5_7;
    private javax.swing.JButton btn5_8;
    private javax.swing.JButton btn6_1;
    private javax.swing.JButton btn6_2;
    private javax.swing.JButton btn6_3;
    private javax.swing.JButton btn6_4;
    private javax.swing.JButton btn6_5;
    private javax.swing.JButton btn6_6;
    private javax.swing.JButton btn6_7;
    private javax.swing.JButton btn6_8;
    private javax.swing.JButton btn7_1;
    private javax.swing.JButton btn7_2;
    private javax.swing.JButton btn7_3;
    private javax.swing.JButton btn7_4;
    private javax.swing.JButton btn7_5;
    private javax.swing.JButton btn7_6;
    private javax.swing.JButton btn7_7;
    private javax.swing.JButton btn7_8;
    private javax.swing.JButton btn8_1;
    private javax.swing.JButton btn8_2;
    private javax.swing.JButton btn8_3;
    private javax.swing.JButton btn8_4;
    private javax.swing.JButton btn8_5;
    private javax.swing.JButton btn8_6;
    private javax.swing.JButton btn8_7;
    private javax.swing.JButton btn8_8;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_actual;
    private javax.swing.JLabel lbl_actual_icon;
    // End of variables declaration//GEN-END:variables
}
